# Generated by Django 5.1 on 2024-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('status', models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado')], default='DESCONECTADO', max_length=15)),
            ],
        ),
    ]
